### ISSUE TITLE
Invalid digit for missing values for a field with a long datatype

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/cds-votable-rust#1]
On this [votable](https://raw.githubusercontent.com/VisIVOLab/SKA-Discovery-Service-Mockup/main/DataLink/DataLink_003.xml) there is a field content_length with a 'long' datatype. The parsing fails with the error `invalid digit` because some rows do have missing values. May be we should make it 0 by default

**Comment by bmatthieu3** [comment]
One VOTable featuring this issue: https://raw.githubusercontent.com/VisIVOLab/SKA-Discovery-Service-Mockup/main/DataLink/DataLink_003.xml

**Comment by fxpineau** [comment]
Seems to be fixed since last merge 51323d0aa954483351d759265519a00e29c2b7a4
