### ISSUE TITLE
Reading sub elements by ref not implemented

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/cds-votable-rust#2]
I do have an obscore votable: https://vo.astron.nl/tap/sync?REQUEST=doQuery&LANG=ADQL&MAXREC=20000000&QUERY=SELECT+TOP+9999+*+FROM+ivoa.obscore+WHERE+CONTAINS%28POINT%28%27ICRS%27%2C+s_ra%2C+s_dec%29%2C+CIRCLE%28%27ICRS%27%2C+214.92068%2C+56.81529%2C+3.03%29%29+%3D+1+

that calls a portion of code not yet implemented.
https://github.com/cds-astro/cds-votable-rust/blob/main/src/values.rs#L390

@fxpineau, @thibaultDumortier - Do you think there is a lot of work to do to support the parsing of this votable ?

**Comment by fxpineau** [comment]
Fixed by commit 21d0356f6d384ae89b961c56c47dd06e6e751fff
