### ISSUE TITLE
Relax the parsing for 1.1/1.2 versioned VOTables

### ISSUE THREAD

**Issue by bmatthieu3** [cds-astro/cds-votable-rust#3]
1.1/1.2 VOTables are not supported and trying to parse them result in panicking

This is unfortunate as these versions seem to be still quite used, e.g. simbad cone search service returns 1.2 votables
```panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Unrecognized version. Actual: '1.2'. Expected: '1.3' or '1.4'")```

It should be great to:
- not panicking but prefer return an error
- provide a relaxed version boolean parameter that could still try to parse the votable even if it is <1.3

**Comment by fxpineau** [comment]
Fixed by commit 41db8bbae47c7a0ca7be89ad7ab05b32ea1ca95a
